### ISSUE TITLE
Auto-reload or manual reload of Spectral ruleset file

### ISSUE THREAD

**Issue by anikitin** [SchwarzIT/spectral-intellij-plugin#10]
I began using your great plugin for OpenAPI spec linting and noticed one thing. If I modify spectral ruleset file in the IDE (the same one I indicated in plugin settings) the changes are not automatically picked up by linter. So if I have API spec file opened I need to close it and then open again to ensure my changes in ruleset are applied.

Would be really nice to have:
* auto-detection of changes in **local** spectral ruleset which is used by plugin
* an option (button) to reload ruleset and re-process open files (it might help if auto-detection is difficult, or ruleset has transitively included rulesets in different files, or ruleset is loaded via HTTP)

**Comment by markbrockhoff** [comment]
Hi @anikitin, thanks for your suggestion.

Actually every execution of the linting plugin will use the latest ruleset. However, this execution will only happen if your IDE schedules it (commonly because of changes to the file or when it's opened).
That's why closing and re-opening it refreshes the linting results.

To overcome having to close and re-open your files while developing your ruleset, I created a PR which adds an asynchronous file watch to the plugin. That will run in the background and mark your open files to be re-linted when the file set as your ruleset changes. This way you can make changes to your ruleset and just switch back to your OpenAPi spec and it should be re-linted with the updated ruleset.

As this process is using a file watcher, it of course only works for local rulesets in your project and not ones that are loaded via http. If you want immediate feedback on those you still need to open and close your OpenAPI spec.

Version 1.0.5, vontaining this feature should be released soon.

P.S. If you're looking for a nice way to develop your own spectral ruleset, feel free to check out our rules repository. There we're developing our rules in isolation together with TDD using unit tests ;)
https://github.com/SchwarzIT/api-linter-rules

**Comment by anikitin** [comment]
@markbrockhoff , thanks, it makes sense.
I will definitely check out your approach of Spectral rules testing...
We have a comprehensive set of rules which we plan to use in our API Governance process, maybe also need to implement some automation to catch regression errors.

Your approach of splitting specs into individual rules and testing in isolation makes a perfect sense.
I am just thinking to have real OpenAPI files to feed to tests and run individual rules against...
We have pretty complex JSonPath expressions, putting it all into JS code will make it hardly understandable...
Need to find some time to play with it. Thanks again for your help, feel free to reach out to discuss.
